import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  // AUTOMATIC SIDEBAR GENERATION
  // This automatically generates the sidebar from your docs folder structure
  // Folders become categories, and files are ordered alphabetically or by frontmatter
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from the 'docs' folder (current directory)
    },
  ],

  // MANUAL SIDEBAR EXAMPLE
  // Uncomment and customize this if you want more control over sidebar structure
  /*
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'core-concepts',
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'API Reference',
        description: 'Complete API documentation for all modules and functions.',
        keywords: ['api', 'reference'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples',
        },
      ],
    },
    {
      type: 'doc',
      id: 'faq',
      label: 'FAQ',
    },
  ],
  */

  // ADDITIONAL SIDEBAR EXAMPLE
  // You can have multiple sidebars for different sections
  /*
  apiSidebar: [
    {
      type: 'category',
      label: 'API Documentation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
  ],
  */
};

export default sidebars;
